kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kates
subjects:
  - kind: ServiceAccount
    name: kates
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kates
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kates
subjects:
  - kind: ServiceAccount
    name: kates
    namespace: default
roleRef:
  kind: ClusterRole
  name: kates
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kates
rules:
  - apiGroups: [""]
    resources:
      - persistentvolumeclaims
    verbs:
      - list
      - get
      - watch
      - update
  - apiGroups: [""]
    resources:
      - persistentvolumes
    verbs:
      - list
      - get
      - update
      - watch
      - create
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: [""]
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
    verbs:
      - '*'
  - apiGroups: ["apps"]
    resources:
      - statefulsets
      - "*"
    verbs:
      - '*'
  - apiGroups: [""]
    resources:
      - namespaces
      - serviceaccounts
      - "*"
    verbs:
      - '*'
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups: ["comcast.github.io"]
    resources:
      - '*'
      - 'khchecks'
      - 'khstates'
    verbs:
      - '*'
  - apiGroups: ["acid.zalan.do"]
    resources:
      - '*'
      - 'postgresqls'
    verbs:
      - '*'
---