kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kates
subjects:
- kind: ServiceAccount
  name: kates
roleRef:
  kind: Role
  name: kates
  apiGroup: rbac.authorization.k8s.io
