apiVersion: nukates.nuos.io/v1alpha1
kind: NuKates
metadata:
  name: nukates
spec:
  cloud: aws # "aws" or "vmware"
  registry:
    image: docker.io/nubeva/nukatesregistry@sha256:7b8791c82690a6b9f936e313d02a9c65451bb38448a611081a138613065632d3
  syslog:
    image: docker.io/nubeva/syslog@sha256:dba73f07bd44b7aad9397d57b56beaeaab15fd1f1fb5be988cae39932fc4645d
  numq:
    kafka:
      pzooInitConfigImage: solsson/kafka-initutils:latest
      pzooContZookeeperImage: solsson/kafka:2.3.0
      zooInitConfigImage: solsson/kafka-initutils:latest
      zooContZookeeperImage: solsson/kafka:2.3.0
      kbrInitConfigImage: solsson/kafka-initutils:latest
      brContImage: docker.io/nubeva/numq@sha256:aee88e439f05f0468eab6026cf00179c0126bc65021f31744661260994084bc8
      topicsContImage: docker.io/nubeva/numq-topics@sha256:e854d7c90f3a40a3c173c37b8a949f38cbd5b990ee07949afba5b530e837c14f
    kafka_controller:
      image: docker.io/nubeva/numq-controller@sha256:3164d5128dbaf674d6644586ad460551b55211be6b05e4e851f4c5b933c48616
    type: kafka
  apig:
    image: docker.io/nubeva/nukatesapig@sha256:241c8e4a1d8b21157de66f0f25d995f35e959a54c7efc4aca9f794b69996d9b0
    muxerImage: docker.io/nubeva/muxer@sha256:79d1be0c66295ef0fc1d435f895adb6f77fe61ebc1ea862037fc7f12b105b2fb
    resetService: true
  putlogapig:
    image: docker.io/nubeva/putlogapig@sha256:f56fffcfe0a25a12f74305fde04fe63566b59e8f2c1ce1e145be169f1201dcf3
  db:
    m3:
      m3Image: quay.io/m3db/m3db-operator:v0.2.0
      m3NodeImage: quay.io/m3db/m3dbnode:v0.14.2
      etcdImage: quay.io/coreos/etcd:v3.3.3
  monitoring:
    promLabelVersion: v0.33.0
    prometheusImage: quay.io/prometheus/prometheus:v2.11.0
    alertManagerImage: quay.io/prometheus/alertmanager:v0.20.0
    configReloaderImage: quay.io/coreos/configmap-reload:v0.0.1
    prometheusConfigReloaderImage: quay.io/coreos/prometheus-config-reloader:v0.33.0
    postgresAcidImage: registry.opensource.zalan.do/acid/spilo-11:1.6-p1
    promImage: quay.io/coreos/prometheus-operator:v0.33.0
    grafImage: nubeva/nuana@sha256:ee047e8297f96d15965295bd9af780c127846eff081af8bb4bee13809b5cc7ab
    grafPartner: Nubeva
    grafPartnerFavicon: public/img/nubeva/favicon.png
    grafDbOperatorImage: docker.io/nubeva/postgres-operator@sha256:84e68f39444ea779974dbccb09e7a71b419fcc17c5e6da3f8ea75b08c44f4687
    ksmMainImage: quay.io/coreos/kube-rbac-proxy:v0.4.1
    ksmSelfImage: quay.io/coreos/kube-rbac-proxy:v0.4.1
    ksmImage: quay.io/coreos/kube-state-metrics:v1.7.2
    neImage: quay.io/prometheus/node-exporter:v0.18.1
    neKubeRbacImage: quay.io/coreos/kube-rbac-proxy:v0.4.1
    promAdaptImage: quay.io/coreos/k8s-prometheus-adapter-amd64:v0.4.1
    kuberhealthyImage: quay.io/comcast/kuberhealthy:2.0.0
    kuberhealthyCheckDeploymentImage: quay.io/comcast/deployment-check:1.0.3
    kuberhealthyCheckHTTPImage: quay.io/comcast/http-check:1.0.0
    kuberhealthyCheckInternalDNSImage: quay.io/comcast/dns-status-check:1.0.0
    kuberhealthyCheckPodRestartsImage: quay.io/comcast/pod-restarts-check:2.0.0
    kuberhealthyCheckPodStatusImage: quay.io/comcast/pod-status-check:1.1.0
  proxy:
    image: quay.io/datawire/ambassador:1.2.2
    hostNetwork: false
  binrepo:
    image: docker.io/nubeva/bin-repo@sha256:5200b05e54cc99ca6c2ee806921cf086261284fed28668ae11851ca44473eb2e
  mongodb:
    image: mongo
    mongoSidecarImage: cvallance/mongo-k8s-sidecar
    mongoExporterImage: ssheehy/mongodb-exporter
  fluentd:
    image: fluent/fluentd-kubernetes-daemonset:v1-debian-syslog
  cfmetrics:
    image: docker.io/nubeva/nukatescfg-metrics@sha256:427a4a5816b526f586c19baa3f1d33e59371dee440b940c6b90565ec6ff40035
