apiVersion: apps/v1
kind: Deployment
metadata:
  name: kates
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kates
  template:
    metadata:
      labels:
        name: kates
    spec:
      serviceAccountName: kates
      containers:
        - name: kates
          # Replace this with the built image name
          image: docker.io/nubeva/nukates:64463ddd9ebe
          command:
          - kates
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kates"
