apiVersion: nukates.nuos.io/v1alpha1
kind: NuConfig
metadata:
  name: nuconfig
spec:
  image: docker.io/nubeva/nukatescfg@sha256:62eebfdcb38d36865a14532f6461bdf57606e44262502c4caca73d41c25635a7
  projects:
  - config:
      support:
        automatic: true
        endpoint: https://i.nuos.io/logs
        option: upload
        token: I2dHIUZnU29ZJnNSalhsZXN2ZzBObnZSOFdCclghRkJwd2piciVZQWZRdGZLWTlsenBEOSFxVDghVFRZRnQ3VFRJYTVtemVaZ3JTbkQmNlFJYnhXNXg1eTZrNjVVVXgycm43Nks0SUZPMHZoc2hXdiNEIXoxMiZ2RDdTYkFCT3I=
    connections: []
    description: Default Project
    dest_groups: []
    name: Default Project
    src_groups: []
    ssldbauthread: eyJ0eXBlIjoia2RiIiwiZG9tYWluIjoiZG9tIiwicmVnaW9uIjoiay5udW9zLmlvIiwiYWsiOiJ1c2VyIiwic2siOiJhdXRoIn0=
    ssldbauthwrite: eyJ0eXBlIjoia2RiIiwiZG9tYWluIjoiZG9tIiwicmVnaW9uIjoiay5udW9zLmlvIiwiYWsiOiJ1c2VyIiwic2siOiJhdXRoIn0=
    uniqueid: 1578954353888641656x2nqze7c8MP
  sensors_limit: 101
